data:
    image: tianon/true
    volumes:
        - /code/build
        - /usr/src
        - /pkg

builder:
    build: .
    volumes:
        - ./pkg:/pkg
    volumes_from:
        - data
    environment:
        - CLANG_VERSION=3.8
        - BUILD_NUMBER=2
    stdin_open: true
    tty: true
    command: ["make","all"]

